<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net9.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>NativeInterop</AssemblyName></PropertyGroup><ItemGroup><Reference Include="sts2"><HintPath>$(Game)/data_sts2_windows_x86_64/sts2.dll</HintPath><Private>false</Private></Reference><Reference Include="GodotSharp"><HintPath>$(Game)/data_sts2_windows_x86_64/GodotSharp.dll</HintPath><Private>false</Private></Reference><Reference Include="NoSuffering"><HintPath>$(Game)/mods/NoSuffering/NoSuffering.dll</HintPath><Private>false</Private></Reference></ItemGroup></Project>
